package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema      string `json:"api_schema"`
	MaterialCode   string `json:"material_code"`
	Plant_Supplier string `json:"plant/supplier"`
	Stock          string `json:"stock"`
	DocumentType   string `json:"document_type"`
	DocumentNo     string `json:"document_no"`
	PlannedDate    string `json:"planned_date"`
	ValidatedDate  string `json:"validated_date"`
	Deleted        bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey        string `json:"connection_key"`
	Result               bool   `json:"result"`
	RedisKey             string `json:"redis_key"`
	Filepath             string `json:"filepath"`
	SalesQuoteCollection struct {
		ObjectID                               string `json:"ObjectID"`
		ID                                     string `json:"ID"`
		BuyerID                                string `json:"BuyerID"`
		Name                                   string `json:"Name"`
		ProcessingTypeCode                     string `json:"ProcessingTypeCode"`
		ProcessingTypeCodeText                 string `json:"ProcessingTypeCodeText"`
		BuyerPartyID                           string `json:"BuyerPartyID"`
		BuyerPartyName                         string `json:"BuyerPartyName"`
		BuyerContactPartyID                    string `json:"BuyerContactPartyID"`
		BuyerContactPartyName                  string `json:"BuyerContactPartyName"`
		ProductRecipientPartyID                string `json:"ProductRecipientPartyID"`
		ProductRecipientPartyName              string `json:"ProductRecipientPartyName"`
		EmployeeResponsiblePartyID             string `json:"EmployeeResponsiblePartyID"`
		EmployeeResponsiblePartyName           string `json:"EmployeeResponsiblePartyName"`
		SalesUnitPartyID                       string `json:"SalesUnitPartyID"`
		SalesUnitPartyName                     string `json:"SalesUnitPartyName"`
		SalesOrganisationID                    string `json:"SalesOrganisationID"`
		SalesOrganisationName                  string `json:"SalesOrganisationName"`
		SalesOfficeID                          string `json:"SalesOfficeID"`
		SalesOfficeName                        string `json:"SalesOfficeName"`
		SalesGroupID                           string `json:"SalesGroupID"`
		SalesGroupName                         string `json:"SalesGroupName"`
		DistributionChannelCode                string `json:"DistributionChannelCode"`
		DistributionChannelCodeText            string `json:"DistributionChannelCodeText"`
		DivisionCode                           string `json:"DivisionCode"`
		DivisionCodeText                       string `json:"DivisionCodeText"`
		SalesTerritoryID                       string `json:"SalesTerritoryID"`
		SalesTerritoryName                     string `json:"SalesTerritoryName"`
		DateTime                               string `json:"DateTime"`
		RequestedFulfillmentStartDateTime      string `json:"RequestedFulfillmentStartDateTime"`
		PriceDateTime                          string `json:"PriceDateTime"`
		TimeZoneCode                           string `json:"TimeZoneCode"`
		TimeZoneCodeText                       string `json:"TimeZoneCodeText"`
		ValidFromDate                          string `json:"ValidFromDate"`
		ValidToDate                            string `json:"ValidToDate"`
		CurrencyCode                           string `json:"CurrencyCode"`
		CurrencyCodeText                       string `json:"CurrencyCodeText"`
		DocumentLanguageCode                   string `json:"DocumentLanguageCode"`
		DocumentLanguageCodeText               string `json:"DocumentLanguageCodeText"`
		DeliveryPriorityCode                   string `json:"DeliveryPriorityCode"`
		DeliveryPriorityCodeText               string `json:"DeliveryPriorityCodeText"`
		IncotermsClassificationCode            string `json:"IncotermsClassificationCode"`
		IncotermsClassificationCodeText        string `json:"IncotermsClassificationCodeText"`
		IncotermsTransferLocationName          string `json:"IncotermsTransferLocationName"`
		ProbabilityPercent                     string `json:"ProbabilityPercent"`
		CancellationReasonCode                 string `json:"CancellationReasonCode"`
		CancellationReasonCodeText             string `json:"CancellationReasonCodeText"`
		OrderReasonCode                        string `json:"OrderReasonCode"`
		OrderReasonCodeText                    string `json:"OrderReasonCodeText"`
		MainDiscount                           string `json:"MainDiscount"`
		NetAmount                              string `json:"NetAmount"`
		NetAmountCurrencyCode                  string `json:"NetAmountCurrencyCode"`
		NetAmountCurrencyCodeText              string `json:"NetAmountCurrencyCodeText"`
		GrossAmount                            string `json:"GrossAmount"`
		GrossAmountCurrencyCode                string `json:"GrossAmountCurrencyCode"`
		GrossAmountCurrencyCodeText            string `json:"GrossAmountCurrencyCodeText"`
		TaxAmount                              string `json:"TaxAmount"`
		TaxAmountCurrencyCode                  string `json:"TaxAmountCurrencyCode"`
		TaxAmountCurrencyCodeText              string `json:"TaxAmountCurrencyCodeText"`
		CashDiscountTermsCode                  string `json:"CashDiscountTermsCode"`
		CashDiscountTermsCodeText              string `json:"CashDiscountTermsCodeText"`
		ConfirmationExistenceIndicator         bool   `json:"ConfirmationExistenceIndicator"`
		ConsistencyStatusCode                  string `json:"ConsistencyStatusCode"`
		ConsistencyStatusCodeText              string `json:"ConsistencyStatusCodeText"`
		LifeCycleStatusCode                    string `json:"LifeCycleStatusCode"`
		LifeCycleStatusCodeText                string `json:"LifeCycleStatusCodeText"`
		CancellationStatusCode                 string `json:"CancellationStatusCode"`
		CancellationStatusCodeText             string `json:"CancellationStatusCodeText"`
		ResultStatusCode                       string `json:"ResultStatusCode"`
		ResultStatusCodeText                   string `json:"ResultStatusCodeText"`
		ApprovalStatusCode                     string `json:"ApprovalStatusCode"`
		ApprovalStatusCodeText                 string `json:"ApprovalStatusCodeText"`
		OrderingStatusCode                     string `json:"OrderingStatusCode"`
		OrderingStatusCodeText                 string `json:"OrderingStatusCodeText"`
		CreditWorthinessStatusCode             string `json:"CreditWorthinessStatusCode"`
		CreditWorthinessStatusCodeText         string `json:"CreditWorthinessStatusCodeText"`
		ReplicationProcessingStatusCode        string `json:"ReplicationProcessingStatusCode"`
		ReplicationProcessingStatusCodeText    string `json:"ReplicationProcessingStatusCodeText"`
		ProductAvailabilityStatusCode          string `json:"ProductAvailabilityStatusCode"`
		ProductAvailabilityStatusCodeText      string `json:"ProductAvailabilityStatusCodeText"`
		PriceCalculationStatusCode             string `json:"PriceCalculationStatusCode"`
		PriceCalculationStatusCodeText         string `json:"PriceCalculationStatusCodeText"`
		PricingProcedureCode                   string `json:"PricingProcedureCode"`
		PricingProcedureCodeText               string `json:"PricingProcedureCodeText"`
		ExternalPriceCalculationStatusCode     string `json:"ExternalPriceCalculationStatusCode"`
		ExternalPriceCalculationStatusCodeText string `json:"ExternalPriceCalculationStatusCodeText"`
		ExternalPricingProcedureCode           string `json:"ExternalPricingProcedureCode"`
		ExternalPricingProcedureCodeText       string `json:"ExternalPricingProcedureCodeText"`
		CreationDateTime                       string `json:"CreationDateTime"`
		LastChangeDateTime                     string `json:"LastChangeDateTime"`
		CreatedBy                              string `json:"CreatedBy"`
		LastChangedBy                          string `json:"LastChangedBy"`
		CreationIdentityUUID                   string `json:"CreationIdentityUUID"`
		LastChangeIdentityUUID                 string `json:"LastChangeIdentityUUID"`
		VersionGroupID                         string `json:"VersionGroupID"`
		VersionID                              string `json:"VersionID"`
		External                               bool   `json:"External"`
		Submit                                 string `json:"Submit"`
		SetAsWon                               string `json:"SetAsWon"`
		SetAsLost                              bool   `json:"SetAsLost"`
		RequestExtData                         string `json:"RequestExtData"`
		PrimaryQuote                           bool   `json:"PrimaryQuote"`
		UpdateOpportunity                      string `json:"UpdateOpportunity"`
		RequestExtFollowup                     bool   `json:"RequestExtFollowup"`
		GrossWeightMeasure                     string `json:"GrossWeightMeasure"`
		GrossWeightUnitCode                    string `json:"GrossWeightUnitCode"`
		GrossWeightUnitCodeText                string `json:"GrossWeightUnitCodeText"`
		NetWeightMeasure                       string `json:"NetWeightMeasure"`
		NetWeightUnitCode                      string `json:"NetWeightUnitCode"`
		NetWeightUnitCodeText                  string `json:"NetWeightUnitCodeText"`
		VolumeMeasure                          string `json:"VolumeMeasure"`
		VolumeUnitCode                         string `json:"VolumeUnitCode"`
		VolumeUnitCodeText                     string `json:"VolumeUnitCodeText"`
		ExternalApprovalStatusCode             string `json:"ExternalApprovalStatusCode"`
		ExternalApprovalStatusCodeText         string `json:"ExternalApprovalStatusCodeText"`
		PlantPartyID                           string `json:"PlantPartyID"`
		PlantPartyName                         string `json:"PlantPartyName"`
		EntityLastChangedOn                    string `json:"EntityLastChangedOn"`
		ETag                                   string `json:"ETag"`
		DataloaderKUT                          string `json:"dataloader_KUT"`
		SalesQuoteItemCollection               struct {
			ObjectID                          string `json:"ObjectID"`
			ParentObjectID                    string `json:"ParentObjectID"`
			QuoteID                           string `json:"QuoteID"`
			ItemID                            string `json:"ItemID"`
			ParentItemID                      string `json:"ParentItemID"`
			AlternativeToItemID               string `json:"AlternativeToItemID"`
			ProcessingTypeCode                string `json:"ProcessingTypeCode"`
			ProcessingTypeCodeText            string `json:"ProcessingTypeCodeText"`
			Description                       string `json:"Description"`
			ProductInternalID                 string `json:"ProductInternalID"`
			ProductBuyerID                    string `json:"ProductBuyerID"`
			ProductStandardID                 string `json:"ProductStandardID"`
			ProductCategoryID                 string `json:"ProductCategoryID"`
			Quantity                          string `json:"Quantity"`
			QuantityMeasureUnitCode           string `json:"QuantityMeasureUnitCode"`
			QuantityMeasureUnitCodeText       string `json:"QuantityMeasureUnitCodeText"`
			StartDateTime                     string `json:"StartDateTime"`
			TimeZoneCode                      string `json:"TimeZoneCode"`
			TimeZoneCodeText                  string `json:"TimeZoneCodeText"`
			ProductRecipientPartyID           string `json:"ProductRecipientPartyID"`
			ProductRecipientPartyName         string `json:"ProductRecipientPartyName"`
			CancellationReasonCode            string `json:"CancellationReasonCode"`
			CancellationReasonCodeText        string `json:"CancellationReasonCodeText"`
			MainPrice                         string `json:"MainPrice"`
			MainPriceCurrencyCode             string `json:"MainPriceCurrencyCode"`
			MainPriceCurrencyCodeText         string `json:"MainPriceCurrencyCodeText"`
			MainPriceBaseQuantity             string `json:"MainPriceBaseQuantity"`
			MainPriceBaseQuantityUnitCode     string `json:"MainPriceBaseQuantityUnitCode"`
			MainPriceBaseQuantityUnitCodeText string `json:"MainPriceBaseQuantityUnitCodeText"`
			MainDiscount                      string `json:"MainDiscount"`
			NetPriceAmount                    string `json:"NetPriceAmount"`
			NetPriceAmountCurrencyCode        string `json:"NetPriceAmountCurrencyCode"`
			NetPriceAmountCurrencyCodeText    string `json:"NetPriceAmountCurrencyCodeText"`
			NetPriceBaseQuantity              string `json:"NetPriceBaseQuantity"`
			NetPriceBaseQuantityUnitCode      string `json:"NetPriceBaseQuantityUnitCode"`
			NetPriceBaseQuantityUnitCodeText  string `json:"NetPriceBaseQuantityUnitCodeText"`
			NetAmount                         string `json:"NetAmount"`
			NetAmountCurrencyCode             string `json:"NetAmountCurrencyCode"`
			NetAmountCurrencyCodeText         string `json:"NetAmountCurrencyCodeText"`
			GrossAmount                       string `json:"GrossAmount"`
			GrossAmountCurrencyCode           string `json:"GrossAmountCurrencyCode"`
			GrossAmountCurrencyCodeText       string `json:"GrossAmountCurrencyCodeText"`
			TaxAmount                         string `json:"TaxAmount"`
			TaxAmountCurrencyCode             string `json:"TaxAmountCurrencyCode"`
			TaxAmountCurrencyCodeText         string `json:"TaxAmountCurrencyCodeText"`
			CashDiscountTermsCode             string `json:"CashDiscountTermsCode"`
			CashDiscountTermsCodeText         string `json:"CashDiscountTermsCodeText"`
			CancellationStatusCode            string `json:"CancellationStatusCode"`
			CancellationStatusCodeText        string `json:"CancellationStatusCodeText"`
			ConsistencyStatusCode             string `json:"ConsistencyStatusCode"`
			ConsistencyStatusCodeText         string `json:"ConsistencyStatusCodeText"`
			LifeCycleStatusCode               string `json:"LifeCycleStatusCode"`
			LifeCycleStatusCodeText           string `json:"LifeCycleStatusCodeText"`
			OrderingStatusCode                string `json:"OrderingStatusCode"`
			OrderingStatusCodeText            string `json:"OrderingStatusCodeText"`
			ConfirmationExistenceIndicator    bool   `json:"ConfirmationExistenceIndicator"`
			CreationDateTime                  string `json:"CreationDateTime"`
			LastChangeDateTime                string `json:"LastChangeDateTime"`
			DeliveryPriorityCode              string `json:"DeliveryPriorityCode"`
			DeliveryPriorityCodeText          string `json:"DeliveryPriorityCodeText"`
			IncotermsClassificationCode       string `json:"IncotermsClassificationCode"`
			IncotermsClassificationCodeText   string `json:"IncotermsClassificationCodeText"`
			IncotermsTransferLocationName     string `json:"IncotermsTransferLocationName"`
			GrossWeightMeasure                string `json:"GrossWeightMeasure"`
			GrossWeightUnitCode               string `json:"GrossWeightUnitCode"`
			GrossWeightUnitCodeText           string `json:"GrossWeightUnitCodeText"`
			NetWeightMeasure                  string `json:"NetWeightMeasure"`
			NetWeightUnitCode                 string `json:"NetWeightUnitCode"`
			NetWeightUnitCodeText             string `json:"NetWeightUnitCodeText"`
			VolumeMeasure                     string `json:"VolumeMeasure"`
			VolumeUnitCode                    string `json:"VolumeUnitCode"`
			VolumeUnitCodeText                string `json:"VolumeUnitCodeText"`
			OrderedQuantity                   string `json:"OrderedQuantity"`
			OrderedQuantityUnitCode           string `json:"OrderedQuantityUnitCode"`
			OrderedQuantityUnitCodeText       string `json:"OrderedQuantityUnitCodeText"`
			PricingProductID                  string `json:"PricingProductID"`
			PlantPartyID                      string `json:"PlantPartyID"`
			PlantPartyName                    string `json:"PlantPartyName"`
			EntityLastChangedOn               string `json:"EntityLastChangedOn"`
			ETag                              string `json:"ETag"`
			SalesQuotePartyCollection         struct {
				ObjectID                                 string `json:"ObjectID"`
				ParentObjectID                           string `json:"ParentObjectID"`
				QuoteID                                  string `json:"QuoteID"`
				PartyID                                  string `json:"PartyID"`
				RoleCode                                 string `json:"RoleCode"`
				RoleCodeText                             string `json:"RoleCodeText"`
				MainIndicator                            bool   `json:"MainIndicator"`
				PartyContactPartyID                      string `json:"PartyContactPartyID"`
				PartyName                                string `json:"PartyName"`
				PartyContactPartyName                    string `json:"PartyContactPartyName"`
				CountryCode                              string `json:"CountryCode"`
				CountryCodeText                          string `json:"CountryCodeText"`
				RegionCode                               string `json:"RegionCode"`
				RegionCodeText                           string `json:"RegionCodeText"`
				CareOfName                               string `json:"CareOfName"`
				StreetPrefixName                         string `json:"StreetPrefixName"`
				AdditionalStreetPrefixName               string `json:"AdditionalStreetPrefixName"`
				HouseID                                  string `json:"HouseID"`
				StreetName                               string `json:"StreetName"`
				StreetSuffixName                         string `json:"StreetSuffixName"`
				AdditionalStreetSuffixName               string `json:"AdditionalStreetSuffixName"`
				DistrictName                             string `json:"DistrictName"`
				CityName                                 string `json:"CityName"`
				AdditionalCityName                       string `json:"AdditionalCityName"`
				StreetPostalCode                         string `json:"StreetPostalCode"`
				StreetPostalCodeText                     string `json:"StreetPostalCodeText"`
				CountyName                               string `json:"CountyName"`
				CompanyPostalCode                        string `json:"CompanyPostalCode"`
				CompanyPostalCodeText                    string `json:"CompanyPostalCodeText"`
				POBoxIndicator                           bool   `json:"POBoxIndicator"`
				POBoxID                                  string `json:"POBoxID"`
				POBoxPostalCode                          string `json:"POBoxPostalCode"`
				POBoxPostalCodeText                      string `json:"POBoxPostalCodeText"`
				POBoxDeviatingCountryCode                string `json:"POBoxDeviatingCountryCode"`
				POBoxDeviatingCountryCodeText            string `json:"POBoxDeviatingCountryCodeText"`
				POBoxDeviatingRegionCode                 string `json:"POBoxDeviatingRegionCode"`
				POBoxDeviatingRegionCodeText             string `json:"POBoxDeviatingRegionCodeText"`
				POBoxDeviatingCityName                   string `json:"POBoxDeviatingCityName"`
				BuildingID                               string `json:"BuildingID"`
				FloorID                                  string `json:"FloorID"`
				RoomID                                   string `json:"RoomID"`
				Phone                                    string `json:"Phone"`
				Mobile                                   string `json:"Mobile"`
				Fax                                      string `json:"Fax"`
				Email                                    string `json:"Email"`
				Web                                      string `json:"Web"`
				CorrespondenceLanguageCode               string `json:"CorrespondenceLanguageCode"`
				CorrespondenceLanguageCodeText           string `json:"CorrespondenceLanguageCodeText"`
				PreferredCommunicationMediumTypeCode     string `json:"PreferredCommunicationMediumTypeCode"`
				PreferredCommunicationMediumTypeCodeText string `json:"PreferredCommunicationMediumTypeCodeText"`
				FirstLineName                            string `json:"FirstLineName"`
				SecondLineName                           string `json:"SecondLineName"`
				ThirdLineName                            string `json:"ThirdLineName"`
				FourthLineName                           string `json:"FourthLineName"`
				ETag                                     string `json:"ETag"`
				SalesQuoteItemScheduleLineCollection     struct {
					ObjectID         string `json:"ObjectID"`
					ParentObjectID   string `json:"ParentObjectID"`
					QuoteID          string `json:"QuoteID"`
					QuoteItemID      string `json:"QuoteItemID"`
					ID               string `json:"ID"`
					TypeCode         string `json:"TypeCode"`
					TypeCodeText     string `json:"TypeCodeText"`
					Quantity         string `json:"Quantity"`
					UnitCode         string `json:"unitCode"`
					UnitCodeText     string `json:"unitCodeText"`
					StartDateTime    string `json:"StartDateTime"`
					EndDateTime      string `json:"EndDateTime"`
					TimeZoneCode     string `json:"timeZoneCode"`
					TimeZoneCodeText string `json:"timeZoneCodeText"`
					ETag             string `json:"ETag"`
				} `json:"SalesQuoteItemScheduleLineCollection"`
			} `json:"SalesQuotePartyCollection"`
		} `json:"SalesQuoteItemCollection"`
	} `json:"SalesQuoteCollection"`
	APISchema      string   `json:"api_schema"`
	Accepter       []string `json:"accepter"`
	SalesQuoteCode string   `json:"sales_quote_code"`
	Deleted        bool     `json:"deleted"`
}
